export const rssSources = [
  'https://zenn.dev/feed',
  'https://qiita.com/popular-items/feed',
  'https://codezine.jp/rss/new/20/index.xml',
  'https://www.publickey1.jp/atom.xml',
  // Medium
  'https://medium.com/feed/tag/ai',
  'https://medium.com/feed/tag/artificial-intelligence',
  'https://medium.com/feed/tag/machine-learning',
  'https://medium.com/feed/tag/deep-learning',
  'https://medium.com/feed/tag/llm',
  'https://medium.com/feed/tag/generative-ai',
  'https://medium.com/feed/tag/nlp',
  'https://medium.com/feed/tag/data-science',
  'https://medium.com/feed/tag/retrieval-augmented-generation',
  'https://medium.com/feed/tag/langchain',
  'https://medium.com/feed/tag/openai',
  'https://medium.com/feed/tag/transformers',
  'https://medium.com/feed/tag/startups',
  'https://medium.com/feed/tag/programming',
  'https://medium.com/feed/tag/cloud-computing',
  'https://medium.com/feed/towards-data-science',
  'https://medium.com/feed/artificial-corner',
  'https://medium.com/feed/mlearning-ai',
]
